storefront/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
    url(r'^create/$',views.CreateAccount.as_view(),name='create'),
    url(r'^details/(?P<pk>\d+)/$',views.DisplayDetails.as_view(),name='details'),
    url(r'^edit/(?P<pk>\d+)/$',views.EditAccount.as_view(),name='edit'),

]

storefront/basket/urls.py
from django.conf.urls import url
from . import views
from orders.views import update_new_order
from django.views.generic import TemplateView

app_name = 'basket'

urlpatterns = [

    url(r'^$',views.BasketMain.as_view(),name='basket'),
    url(r'^x/$',views.BasketTemp.as_view(),name='basketx'),
    url(r'^(?P<pk>\d+)/$',views.BasketDetail.as_view(),name='basket_detail'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/delete/$',views.BasketBouquetDelete.as_view(),name='delete_bouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/tdelete/$',views.BasketTBouquetDelete.as_view(),name='delete_tbouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/rdelete/$',views.BasketRBouquetDelete.as_view(),name='delete_rbouquet'),
    url(r'^confirm/create/$',views.CreateAccountFromBasket.as_view(),name='purchase'),
    url(r'^confirm/final/$',update_new_order,name='purchase_final'),
    url(r'^confirm/(?P<pk>\d+)/update/$',views.UpdateAccountFromBasket.as_view(),name="update_purchase"),

    # url(r'^create/(?P<b_model>[-\w]+)/(?P<pk>\d+)/$',views.CreateBasket.as_view(),name='create_basket'),
]

storefront/orders/urls.py
from django.conf.urls import url
from . import views


app_name = 'orders'

urlpatterns = [
    url(r'^detail/(?P<pk>\d+)/$',views.OrderDetail.as_view(),name='detail'),
]

storefront/products/urls.py
from django.conf.urls import url
from . import views
from themed_products.views import RandomCreateThemedBouquet

app_name = 'products'

urlpatterns = [

    url(r'^main/$',RandomCreateThemedBouquet.as_view(),name="shop"),
    url(r'^range/$',views.RangeHome.as_view(),name='range'),
    url(r'^tailor/$',views.create_bouquet,name='tailor'),
    url(r'^(?P<bouquet_id>\d+)/create/single/$',views.FlowerCreate.as_view(),name="create_single"),
    url(r'^(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/single/$',views.FlowerDelete.as_view(),name="delete_flower"),
    url(r'^bouquet/(?P<pk>\d+)/$',views.BouquetDetail.as_view(),name="detail_bouquet"),
    url(r'^bouquetup/(?P<pk>\d+)/$',views.update_bouquet,name='update_bouquet_new'),
    url(r'^bouquet/(?P<pk>\d+)/delete/$',views.DeleteBouquet.as_view(),name="delete_bouquet"),
    url(r'^bouquetb/(?P<pk>\d+)/$',views.BasketBouquetDetail.as_view(),name="basket_bouquet"),

    # url(r'^bouquet/(?P<pk>\d+)/update/$',views.UpdateBouquet.as_view(),name="update_bouquet"),
    # url(r'^bouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateBouquetTwo.as_view(),name="update_bouquet_two"),
]

storefront/storefront/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    url(r'^$',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls, name='myadmin'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^loggedin/$',views.LoggedInPage.as_view(),name='logged_in'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^about/$',views.AboutPage.as_view(),name='about'),
    url(r'^basket/',include('basket.urls',namespace='basket')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^themed_products/',include('themed_products.urls',namespace='themed_products')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^range_products/',include('range_products.urls',namespace='range_products')),
    url(r'^enquiry/',include('enquiry.urls',namespace='enquiry')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storefront/themed_products/urls.py
from django.conf.urls import url
from . import views

app_name = 'themed_products'

urlpatterns = [

    url(r'^create/$',views.CreateThemedBouquet.as_view(),name="create_themed"),
    url(r'^tbouquetty/update/(?P<b_id>\d+)/$',views.CreateTypeTheme.as_view(),name="update_type"),
    url(r'^tbouquetc/update/(?P<b_id>\d+)/$',views.CreateColourTheme.as_view(),name="update_colour"),
    url(r'^tbouquetth/(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/$',views.DeleteTheme.as_view(),name="delete_theme"),
    url(r'^tbouquet/(?P<pk>\d+)/$',views.ThemedBouquetDetail.as_view(),name="themed_detail"),
    url(r'^tbouquetb/(?P<pk>\d+)/$',views.BasketThemedBouquetDetail.as_view(),name="basket_tbouquet"),
    url(r'^tbouquet/(?P<pk>\d+)/update/$',views.update_themed_bouquet,name='update_tbouquet'),
    url(r'^tbouquet/(?P<pk>\d+)/delete/$',views.DeleteThemedBouquet.as_view(),name="delete_tbouquet"),
    url(r'^rbouquet/(?P<pk>\d+)/update/$',views.RandomUpdateThemedBouquet.as_view(),name="random_update"),

    # url(r'^tbouquet/(?P<pk>\d+)/update/$',views.UpdateTBouquet.as_view(),name="update_tbouquet"),
    # url(r'^tbouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateTBouquetTwo.as_view(),name="update_tbouquet_two"),
    ]

storefront/themed_products/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib import auth
from decimal import Decimal

from orders.models import Order
from basket.models import Basket
from products.models import (Type,Colour,)

from django import template
register = template.Library()


THEME_CHOICES = [

    ('Type', 'Type'),
    ('Colour', 'Colour'),
    ('Type and Colour', 'Type and Colour'),
]

# Create your models here.

class Size(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2,max_digits=8)

    def __str__(self):
        return self.name


class ThemedBouquet(models.Model):
    theme_name = models.CharField(max_length=50,null=True,blank=True,choices=THEME_CHOICES)
    price = models.DecimalField(decimal_places=2,max_digits=8,default=Decimal('0.00'))
    basket = models.ForeignKey(Basket,on_delete=models.CASCADE,blank=True,null=True,related_name='themed_bouquet')
    size = models.ForeignKey(Size,on_delete=models.CASCADE,blank=True,null=True,related_name='bouquet')
    order = models.ForeignKey(Order,on_delete=models.CASCADE,blank=True,null=True,related_name='tbouquet')

    def __str__(self):
        return f"Themed Bouquet #{self.pk}"

    def get_absolute_url(self):
        return reverse('themed_products:themed_detail',kwargs= {'pk':self.pk})


class Theme(models.Model):
    name = models.CharField(max_length=50)
    colour = models.ForeignKey(Colour,on_delete=models.CASCADE,null=True,blank=True,related_name='theme_colour')
    type = models.ForeignKey(Type,on_delete=models.CASCADE,null=True,blank=True,related_name='theme_type')
    t_bouquet = models.ForeignKey(ThemedBouquet,on_delete=models.CASCADE,null=True,blank=True,related_name='theme')

    def __str__(self):
        return f"Theme: By {self.t_bouquet.theme_name}"

storefront/themed_products/forms.py
from django import forms
from .models import (ThemedBouquet, Theme, Size,)
from products.models import (Type, Colour,)
from django.forms import ModelForm



class CreateThemedBouquetForm(ModelForm):

    size = forms.ModelChoiceField(queryset=Size.objects.all())

    class Meta:
        model = ThemedBouquet
        exclude = ('basket','price','order',)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['size'].label = 'Select your bouquet size:'


class CreateTypeThemeForm(ModelForm):

    b_id_num = forms.IntegerField(max_value=None,min_value=1,widget=forms.HiddenInput())
    type = forms.ModelChoiceField(queryset=Type.objects.all())

    class Meta:
        model = Theme
        exclude = ('name','colour','t_bouquet')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['type'].label = 'Select a new flower type:'


class CreateColourThemeForm(ModelForm):

    b_id_num = forms.IntegerField(max_value=None,min_value=1,widget=forms.HiddenInput())
    colour = forms.ModelChoiceField(queryset=Colour.objects.all())

    class Meta:
        model = Theme
        exclude = ('name','type','t_bouquet')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['colour'].label = 'Select a new colour:'



class UpdateTBouquetForm(ModelForm):

    class Meta:
        model = ThemedBouquet
        exclude = ('price','basket','theme_name','size','order',)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

storefront/themed_products/views.py
from django.shortcuts import render,redirect
from django.views.generic import (CreateView, DetailView,
                                UpdateView, DeleteView,)
from django.urls import reverse_lazy, reverse
from .models import (Theme,ThemedBouquet,
                    Size,)
from products.models import (Type,Colour,)
from basket.models import Basket
from . import forms
import re


# Create your views here.

class RandomCreateThemedBouquet(CreateView):
    model = ThemedBouquet
    fields = ()
    template_name = 'products/shop_main.html'

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.save()
        return redirect('themed_products:random_update', self.object.id)


class RandomUpdateThemedBouquet(UpdateView):
    model = ThemedBouquet
    fields = ('price',)
    template_name = 'themed_products/update_random.html'


class CreateThemedBouquet(CreateView):
    model = ThemedBouquet
    form_class = forms.CreateThemedBouquetForm
    template_name = 'themed_products/create_themed_bouquet.html'

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.price = self.object.size.price
        self.object.save()
        return super().form_valid(form)


class ThemedBouquetDetail(DetailView):
    model = ThemedBouquet
    template_name = 'themed_products/themed_detail.html'


class BasketThemedBouquetDetail(DetailView):
    model = ThemedBouquet
    template_name = 'themed_products/basket_tbouquet_detail.html'


class CreateTypeTheme(CreateView):
    model = Type
    form_class = forms.CreateTypeThemeForm
    template_name = 'themed_products/update_theme.html'

    def get_initial(self,**kwargs):
        initial = super().get_initial()
        b3 = self.kwargs['b_id']
        print(f"b3: {b3}")
        initial['b_id_num'] = b3
        return initial

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        b3 = self.kwargs['b_id']
        context['bouq'] = b3
        return context

    def get_success_url(self,**kwargs):
        success_url = reverse_lazy('themed_products:themed_detail', kwargs={'pk':self.object.t_bouquet.pk})
        return success_url

    def form_valid(self,form):
        self.object = form.save(commit=False)
        x = form.cleaned_data['b_id_num']
        self.object.t_bouquet = ThemedBouquet.objects.get(id__iexact=x)
        self.object.save()
        return super().form_valid(form)


class CreateColourTheme(CreateView):
    model = Colour
    form_class = forms.CreateColourThemeForm
    template_name = 'themed_products/update_theme.html'

    def get_initial(self,**kwargs):
        initial = super().get_initial()
        b3 = self.kwargs['b_id']
        initial['b_id_num'] = b3
        return initial

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        b3 = self.kwargs['b_id']
        context['bouq'] = b3
        return context

    def get_success_url(self,**kwargs):
        success_url = reverse_lazy('themed_products:themed_detail', kwargs={'pk':self.object.t_bouquet.pk})
        return success_url

    def form_valid(self,form):
        self.object = form.save(commit=False)
        x = form.cleaned_data['b_id_num']
        self.object.t_bouquet = ThemedBouquet.objects.get(id__iexact=x)
        self.object.save()
        return super().form_valid(form)


class DeleteTheme(DeleteView):
    model = Theme
    template_name = 'themed_products/delete_theme.html'

    def get_success_url(self,**kwargs):
        b1 = self.request.META.get('HTTP_REFERER')
        b2 = re.findall(r'/\d+',b1)[-1]
        b3 = re.findall(r'\d+',b2)[0]
        success_url = reverse_lazy('themed_products:themed_detail',kwargs={'pk':b3})
        return success_url

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        b1 = self.request.META.get('HTTP_REFERER')
        b2 = re.findall(r'/\d+',b1)[-1]
        b3 = re.findall(r'\d+',b2)[0]
        context['prev'] = b3
        return context


class DeleteThemedBouquet(DeleteView):
    model = ThemedBouquet
    template_name = 'themed_products/delete_tbouquet.html'
    success_url = reverse_lazy('products:shop')


def update_themed_bouquet(request,pk):
    bpk = pk
    object = ThemedBouquet.objects.get(id=bpk)
    update_form_t = forms.UpdateTBouquetForm()
    update_form_t.instance = object

    if request.method == "POST":
        update_form_t = forms.UpdateTBouquetForm(request.POST)

        if update_form_t.is_valid():
            x = Basket.objects.get_or_create(user=request.user)[0]
            x.save()
            object.basket = x
            object.save()
            print("Tbouquet updated")
            return redirect('basket:basket')
        else:
            print("Error - form invalid")

    return render(request,'themed_products/update_tbouquet.html', {'update_form_t': update_form_t,'object_pk':pk})





### Update (condition: user doesn't have basket):

# class UpdateTBouquet(UpdateView):
#     model = ThemedBouquet
#     form_class = forms.UpdateTBouquetForm
#     template_name = 'themed_products/update_tbouquet.html'
#
#     def get_success_url(self):
#         success_url = reverse_lazy('basket:create_basket', kwargs={'b_model':'tb','pk':self.object.pk})
#         return success_url


### Update (condition: user already has basket):

# class UpdateTBouquetTwo(UpdateView):
#     model = ThemedBouquet
#     form_class = forms.UpdateTBouquetForm
#     template_name = 'themed_products/update_tbouquet.html'
#     success_url = reverse_lazy('basket:basket')
#
#     def form_valid(self,form):
#         self.object = form.save(commit=False)
#         self.object.basket = self.request.user.customer_basket
#         self.object.save()
#         return super().form_valid(form)

storefront/themed_products/templates/themed_products/basket_tbouquet_detail.html
{% extends 'site_base.html' %}


{% block content_block %}

<br><br>
<div class="container">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image thumb-border-full">
        <br><br><br>
        <h5 class="tb_title">Your bouquet:</h5>
        <br><br>
        <br>

        {% if object.theme_name %}

            <h6>{{object}}</h6>
            <h6>Theme: By {{object.theme_name}}</h6>
            <h6>Size: {{object.size}}</h6>
            <h6>Price: £{{object.price}}</h6>

            <br>

        {% else %}

            <h6>{{object}}</h6>
            <h6>Style: Random</h6>
            <h6>Price: £{{object.price}}</h6>

            <br>

        {% endif %}

          {% if object.theme_name == 'Type' %}
          <br>
            <h6 class="tb_title col-md-3">Your flower types:</h6>
            <br><br>
            {% for x in object.theme.all %}
              {{x.type}}
              <br><br>
              {% endfor %}

          {% elif object.theme_name == 'Colour' %}
          <br>
            <h6 class="tb_title col-md-3">Your bouquet colours:</h6>
            <br><br>
            {% for x in object.theme.all %}
              {{x.colour}}
              <br><br>
              {% endfor %}

           {% elif object.theme_name == 'Type and Colour' %}
           <br>
           <h6 class="tb_title col-md-3">Your flower types:</h6>
           <br><br>
               {% for x in object.theme.all %}
                 {% if x.type %}
                   {{x.type}}
                   <br><br>
                  {% endif %}
                {% endfor %}
            <br><br>
            <h6 class="tb_title col-md-3">Your bouquet colours:</h6>
            <br><br>
            {% for x in object.theme.all %}
              {% if x.colour %}
              {{x.colour}}
              <br><br>
              {% endif %}
              {% endfor %}

            {% else %}
            <br>
            {% endif %}

        <br>

        {% if object.basket %}
        <a class="btn btn-outline-primary" href="{% url 'basket:basket' %}">Back to basket</a>
        {% else %}
        <a class="btn btn-outline-primary" href="{% url 'orders:detail' pk=object.order.pk %}">Back to order</a>
        {% endif %}

        <br><br><br>

    </div>
  </div>
</div>
<br>

{% endblock %}

storefront/themed_products/templates/themed_products/create_themed_bouquet.html
{% extends 'site_base.html' %}
{% load bootstrap3 %}

{% block content_block %}

<div class="container-fluid" style="float:none; margin:auto;">
  <br><br><br>
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-lg-offset-3 col-md-12 col-sm-12 col-xs-12 formimage text-cen">
        <br><br><br>
        <h4 class="tb_title b-gr txt-white">Choose your bouquet theme and size</h4>
        <br><br><br>
        <form class="txt-gr" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <br><br>
          <input type="submit" class="btn btn-success" value="Confirm">
        </form>
        <br><br>
    </div>
  </div>
</div>


{% endblock %}

storefront/themed_products/templates/themed_products/delete_tbouquet.html
{% extends 'site_base.html' %}

{% block content_block %}

<br><br>
<br>
<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image text-cen">
      <br><br><br>
      <h5>Are you sure you want to delete your bouquet?</h5>
      <br><br>
      <form method="POST">
        {% csrf_token %}
          <br>
        <input type="submit" class="btn btn-outline-success" value="Delete">
      </form>
      <br>
      <h6><a class="btn btn-outline-danger" href="{% url 'themed_products:themed_detail' pk=themedbouquet.pk %}">Cancel</a></h6>
      <br><br><br>
    </div>
  </div>
</div>

{% endblock %}

storefront/themed_products/templates/themed_products/delete_theme.html
{% extends 'site_base.html' %}

{% block content_block %}

<br><br>
<br>
<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image text-cen">
      <br><br><br>
      {% if object.colour %}
          <h5>Are you sure you want to delete this colour?</h5>
          <br><br>
          <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-success" value="Delete">
          </form>
      {% else %}
          <h5>Are you sure you want to delete this type?</h5>
          <br><br>
          <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-success" value="Delete">
          </form>
      {% endif %}
      <br>
      <h6><a class="btn btn-outline-danger" href="{% url 'themed_products:themed_detail' pk=prev %}">Cancel</a></h6>
      <br><br>
{% endblock %}

storefront/themed_products/templates/themed_products/delete_themed.html
{% extends 'site_base.html' %}

{% block content_block %}

<h5>Are you sure you want to delete your bouquet?</h5>

<form method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-success" value="Delete">
</form>

<h6><a class="btn btn-outline-danger" href="{% url 'themed_products:themed_detail' pk=themedbouquet.pk %}">Cancel</a></h6>


{% endblock %}

storefront/themed_products/templates/themed_products/themed_detail.html
{% extends 'site_base.html' %}


{% block content_block %}

<br><br>
<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image text-cen">
      <br><br><br>
      <h4 class="tb_title">Your bouquet</h4>
      <br><br><br>

        {% if object.theme_name %}

          <div class="container-fluid text-cen cen">
                <h6>{{object}}</h6>
                <h6>Theme: By {{object.theme_name}}</h6>
                <h6>Size: {{object.size}}</h6>
                <h6>Price: £{{object.price}}</h6>
          </div>

        {% else %}

        <div class="container-fluid text-cen cen">
                <h6>{{object}}</h6>
                <h6>Style: Random</h6>
                <h6>Price: £{{object.price}}</h6>
          </div>

        {% endif %}

        <br>

        {% if object.theme_name == 'Type' %}
          <h6 class="tb_title col-md-3">Your flowers:</h6>
          <br><br><br>
          {% if object.theme.count > 0 %}
            {% for x in object.theme.all %}
              {{x.type|title}}
              <br><br>
              <a class="btn btn-outline-danger btn-sm tiny" href="{% url 'themed_products:delete_theme' bouquet_id=object.pk pk=x.pk %}">Delete</a>
              <br><br>
              {% endfor %}
              {% else %}
              <p>No types yet</p>
              <br><br>
              {% endif %}
        {% else %}
          <br><br>
          {% endif %}

        {% if object.theme_name == 'Colour' %}
          <h6 class="tb_title col-md-3">Your colours:</h6>
          <br><br><br>
            {% if object.theme.count > 0 %}
              {% for x in object.theme.all %}
                {{x.colour|title}}
                <br><br>
                <a class="btn btn-outline-danger btn-sm tiny" href="{% url 'themed_products:delete_theme' bouquet_id=object.pk pk=x.pk %}">Delete</a>
                <br><br>
                {% endfor %}
                {% else %}
                <p>No colours yet</p>
                <br><br>
                {% endif %}
        {% else %}
          <br><br>
          {% endif %}


        {% if object.theme_name == 'Type and Colour' %}

            {% if object.theme.all.count > 0 %}
              <h6 class="tb_title col-md-3">Your theme flowers:</h6>
              <br><br><br>
                  {% for x in object.theme.all %}
                    {% if x.type %}
                      {{x.type|title}}
                      <br><br>
                      <a class="btn btn-outline-danger btn-sm tiny" href="{% url 'themed_products:delete_theme' bouquet_id=object.pk pk=x.pk %}">Delete</a>
                      <br><br>
                      {% endif %}
                    {% endfor %}


            {% else %}
            <h6 class="tb_title col-md-3">Your theme flowers:</h6>
            <br><br>
            <p>No flowers yet</p>
            {% endif %}


            {% if object.theme.all.count > 0 %}
                <br>
                <h6 class="tb_title col-md-3">Your theme colours:</h6>
                <br><br><br>
                  {% for x in object.theme.all %}
                    {% if x.colour %}
                      {{x.colour|title}}
                      <br><br>
                      <a class="btn btn-outline-danger btn-sm tiny" href="{% url 'themed_products:delete_theme' bouquet_id=object.pk pk=x.pk %}">Delete</a>
                      <br><br>
                      {% endif %}
                    {% endfor %}

              {% else %}
                <br><br>
                <h6 class="tb_title col-md-3">Your theme colours:</h6>
                <br><br>
                <p>No colours yet</p>
                <br><br>
                {% endif %}

        {% endif %}
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-sm-12 col-xs-12 text-cen">
      <div class="row text-cen cen">

          <div class="col text-cen">
              <h5><a class="btn btn-outline-danger" href="{% url 'themed_products:delete_tbouquet' pk=object.pk %}">Discard all</a></h5>
          </div>

          <div class="col text-cen">
              {% if object.theme_name == 'Type' %}
              <h5><a class="btn btn-outline-primary" href="{% url 'themed_products:update_type' b_id=object.pk %}">Add a flower</a></h5>

              {% elif object.theme_name == 'Colour' %}
              <h5><a class="btn btn-outline-primary" href="{% url 'themed_products:update_colour' b_id=object.pk %}">Add a colour</a></h5>

              {% elif object.theme_name == 'Type and Colour' %}
              <h5><a class="btn btn-outline-primary" href="{% url 'themed_products:update_type' b_id=object.pk %}">Add a flower</a></h5>
              <h5><a class="btn btn-outline-primary" href="{% url 'themed_products:update_colour' b_id=object.pk %}">Add a colour</a></h5>

              {% else %}
              <p></p>
              {% endif %}
            </div>

            <div class="col text-cen">
                {% if user.customer_basket %}
                  <h5><a class="btn btn-outline-success" href="{% url 'themed_products:update_tbouquet' pk=object.pk %}">Save bouquet</a></h5>
                {% else %}
                  <h5><a class="btn btn-outline-success" href="{% url 'themed_products:update_tbouquet' pk=object.pk %}">Save bouquet</a></h5>
                {% endif %}
            </div>

        </div>
      </div>
    </div>
  </div>
<br>
{% endblock %}

storefront/themed_products/templates/themed_products/update_tbouquet.html
{% extends 'site_base.html' %}

{% block content_block %}

<br><br><br>
<br>

<div class="container">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-sm-12 col-xs-6 pale-image thumb-border-full">
        <br><br>

        {% if user.is_authenticated %}
        <form method="post">
          {% csrf_token %}
          {{update_form_t.as_p}}
          <input type="submit" class="btn btn-outline-success" value="Add to Basket">
          <br><br>
        </form>

        <h6><a class="btn btn-outline-danger" href="{% url 'themed_products:themed_detail' pk=object_pk %}">Back to bouquet</a></h6>
        <br><br>

        {% else %}
        <h5>Please sign up to save your bouquet!</h5>
        <br>
        <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">Sign Up</a>
        <br><br>
        <h6><a class="btn btn-outline-danger" href="{% url 'themed_products:themed_detail' pk=object_pk %}">Back to bouquet</a></h6>
        <br><br>
        {% endif %}
    </div>
  </div>
</div>

{% endblock %}

storefront/themed_products/templates/themed_products/update_type_theme.html
{% extends 'site_base.html' %}
{% load bootstrap3 %}


{% block content_block %}


<h5>Add colours/types:</h5>

<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-outline-warning" value="Add to bouquet">
</form>

{% endblock %}

<h6><a class='btn btn-outline warning' href="{% url 'themed_products:themed_detail' pk=self.t_bouquet.pk %}">Save and go back</a></h6>