storefront/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
    url(r'^create/$',views.CreateAccount.as_view(),name='create'),
    url(r'^details/(?P<pk>\d+)/$',views.DisplayDetails.as_view(),name='details'),
    url(r'^edit/(?P<pk>\d+)/$',views.EditAccount.as_view(),name='edit'),

]

storefront/basket/urls.py
from django.conf.urls import url
from . import views
from orders.views import update_new_order
from django.views.generic import TemplateView

app_name = 'basket'

urlpatterns = [

    url(r'^$',views.BasketMain.as_view(),name='basket'),
    url(r'^x/$',views.BasketTemp.as_view(),name='basketx'),
    url(r'^(?P<pk>\d+)/$',views.BasketDetail.as_view(),name='basket_detail'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/delete/$',views.BasketBouquetDelete.as_view(),name='delete_bouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/tdelete/$',views.BasketTBouquetDelete.as_view(),name='delete_tbouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/rdelete/$',views.BasketRBouquetDelete.as_view(),name='delete_rbouquet'),
    url(r'^confirm/create/$',views.CreateAccountFromBasket.as_view(),name='purchase'),
    url(r'^confirm/final/$',update_new_order,name='purchase_final'),
    url(r'^confirm/(?P<pk>\d+)/update/$',views.UpdateAccountFromBasket.as_view(),name="update_purchase"),

    # url(r'^create/(?P<b_model>[-\w]+)/(?P<pk>\d+)/$',views.CreateBasket.as_view(),name='create_basket'),
]

storefront/enquiry/urls.py
from django.conf.urls import url
from . import views

app_name = 'enquiry'

urlpatterns = [
    url(r'^$',views.CreateEnquiry.as_view(),name="new_enquiry"),
    url(r'^success/$',views.SuccessView.as_view(),name="success"),
]

storefront/products/urls.py
from django.conf.urls import url
from . import views
from themed_products.views import RandomCreateThemedBouquet

app_name = 'products'

urlpatterns = [

    url(r'^main/$',RandomCreateThemedBouquet.as_view(),name="shop"),
    url(r'^range/$',views.RangeHome.as_view(),name='range'),
    url(r'^tailor/$',views.create_bouquet,name='tailor'),
    url(r'^(?P<bouquet_id>\d+)/create/single/$',views.FlowerCreate.as_view(),name="create_single"),
    url(r'^(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/single/$',views.FlowerDelete.as_view(),name="delete_flower"),
    url(r'^bouquet/(?P<pk>\d+)/$',views.BouquetDetail.as_view(),name="detail_bouquet"),
    url(r'^bouquetup/(?P<pk>\d+)/$',views.update_bouquet,name='update_bouquet_new'),
    url(r'^bouquet/(?P<pk>\d+)/delete/$',views.DeleteBouquet.as_view(),name="delete_bouquet"),
    url(r'^bouquetb/(?P<pk>\d+)/$',views.BasketBouquetDetail.as_view(),name="basket_bouquet"),

    # url(r'^bouquet/(?P<pk>\d+)/update/$',views.UpdateBouquet.as_view(),name="update_bouquet"),
    # url(r'^bouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateBouquetTwo.as_view(),name="update_bouquet_two"),
]

storefront/storefront/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    url(r'^$',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls, name='myadmin'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^loggedin/$',views.LoggedInPage.as_view(),name='logged_in'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^about/$',views.AboutPage.as_view(),name='about'),
    url(r'^basket/',include('basket.urls',namespace='basket')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^themed_products/',include('themed_products.urls',namespace='themed_products')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^range_products/',include('range_products.urls',namespace='range_products')),
    url(r'^enquiry/',include('enquiry.urls',namespace='enquiry')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storefront/templates/about.html
{% extends 'site_base.html' %}
{% load static %}

{% block content_block %}

<br>
<img style="max-width:100%;height:auto;" src="{% static "images/titles/aboutpagetitleJPG.jpg" %}" alt="Error loading photo">
<br><br>


  <div class="container width-full">
    <div class="row">
      <div class="col-lg-6 col-sm-6 col-xs-6 thumb-border-full">
        <br>
        <h3 class="tb_title">Our story</h3>
          <br><br>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-6 thumb-border-full">
          <br>
            <h3 class="tb_title">Contact</h3>
            <br><br>
            <p>Email: our-email@helloworld.com, or fill out a <a href="{% url 'enquiry:new_enquiry' %}">contact form</a>.</p>
            <p>Address: 59 High Street, The City, PO5T CDE.</p>
            <p>Tel: 09472 100200</p>
            <p>Socials:</p>
            <div class="container">
              <table class="icons cen text-cen">
                <tr>
                  <td id="twitter-box">
                    <a href="https://twitter.com/?lang=en-gb">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                      <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                    </svg>
                    </a>
                  </td>
                  <td>
                    <a href="https://www.instagram.com/">
                      <img class="img-fluid" src="{% static '/images/logos/insta-icon-bigger.jpg' %}" alt="Insta">
                    </a>
                  </td>
                  <td>
                    <a href="https://www.facebook.com/">
                      <img class="img-fluid" src="{% static '/images/logos/fblogo.jfif' %}" alt="Facebook">
                    </a>
                  </td>
                </tr>
              </table>
              </div>
              <br><br>
          </div>
        </div>
      </div>
      <br>
      <div class="cen text-cen">
          <a class="btn btn-outline-primary" href="{% url 'home' %}">Home</a>
      </div>
<br><br>

{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">

storefront/templates/home.html
{% extends "site_base.html" %}
{% load static %}

{% block content_block %}
<br>
  {% block login_notification %}{% endblock %}
  {% block logout_notification %}{% endblock %}

  <img src="{% static "images/titles/homepage2.jpg" %}" style="max-width:100%;height:auto;" alt="Error loading photo">
<br><br>

  <div class="container width-full" style="padding-left:0px;padding-right:0px;">
    <div class="row">
      <div class="col-lg-6 col-sm-6 col-xs-6">
      <a href="{% url 'products:shop' %}">
        <img class="img-fluid" src="{% static "images/titles/homeshop2edit.jpg" %}" alt="Shop">
      </a>
      <br><br>
      </div>
      <div class="col-lg-6 col-sm-6 col-xs-6">
      <a href="{% url 'about' %}">
        <img class="img-fluid" src="{% static "images/titles/abouttitle.jpg" %}" alt="About us">
      </a>
      <br><br>
      </div>
    <br><br>
    </div>
    <br>
  </div>

{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">

storefront/templates/logged_in.html
{% extends "home.html" %}

{% block login_notification %}
<div class="container">
  <h4>You are now logged in!</h4>
</div>

{% endblock %}

storefront/templates/site_base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/css_master.css" %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Marck+Script&family=Xanh+Mono&display=swap" rel="stylesheet">
  </head>

<body>

  <nav class="navbar" role="navigation" id="navbar">

      <ul class="nav navbar-nav base-link" style="padding-left:5px;clear:none;">

        <li class="base-link"><a class="navbar-brand mybrand" href="{% url 'home' %}">Rosy</a></li>
        <li class="base-link w y"><a class="mylink" href="{% url 'home' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
  </svg></a></li>
        <li class="base-link x y"><a class="mytxtlink" href="{% url 'products:shop' %}">Shop</a></li>
        <li class="base-link x y"><a class="mytxtlink" href="{% url 'about' %}">About</a></li>
      </ul>

      <ul class="mytxtlink nav navbar-nav base-link" style="padding-right:5px;clear:none;">
      {% if user.is_authenticated %}

          {% if user.customer_account %}
                {% if user.customer_basket %}
            <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:details' pk=user.customer_account.pk %}">Account</a></li>
            <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:logout' %}">Log Out</a></li>
            <li class="base-link x z"><a class="mylink" href="{% url 'basket:basket' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5H2z"/>
    </svg></a></li>
                {% else %}
            <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:details' pk=user.customer_account.pk %}">Account</a></li>
            <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:logout' %}">Log Out</a></li>
            <li class="base-link x z"><a class="mylink" href="{% url 'basket:basketx' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5H2z"/>
    </svg></a></li>
                {% endif %}
          {% elif user.customer_basket %}
          <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:create' %}">Account</a></li>
          <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:logout' %}">Log Out</a></li>
          <li class="base-link x z"><a class="mylink" href="{% url 'basket:basket' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5H2z"/>
  </svg></a></li>
          {% else %}
          <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:create' %}">Account</a></li>
          <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:logout' %}">Log Out</a></li>
          <li class="base-link x z"><a class="mylink" href="{% url 'basket:basketx' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5H2z"/>
  </svg></a></li>
          {% endif %}

    {% else %}
      <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:login' %}">Log In</a></li>
      <li class="base-link x z"><a class="mytxtlink" href="{% url 'accounts:signup' %}">Sign Up</a></li>
      <li class="base-link x z"><a class="mylink" href="{% url 'basket:basketx' %}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5H2z"/>
</svg></a></li>
    {% endif %}
        </ul>

  </nav>

    <div class="container">
      {% block content_block %}
      {% endblock %}
    </div>


{% if request.user.is_superuser %}
  <nav class="navbar mynavbtm fixed-bottom">
    <div class="navbar-nav fixed-bottom">
        <li><a class="mylink smol" href="{% url 'admin:login' %}">admin</a></li>
    </div>
  </nav>
{% endif %}


</body>


  <script src={% static "js/js_master.js" %}>
  </script>
  <script src="http://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


</html>

storefront/templates/thanks.html
{% extends "home.html" %}

{% block logout_notification %}
<div class="container">
  <h5>You are now logged out.</h5>
  <h4>Thanks for visiting us today, come back soon!</h4>
</div>
{% endblock %}