storefront/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
    url(r'^create/$',views.CreateAccount.as_view(),name='create'),
    url(r'^details/(?P<pk>\d+)/$',views.DisplayDetails.as_view(),name='details'),
    url(r'^edit/(?P<pk>\d+)/$',views.EditAccount.as_view(),name='edit'),

]

storefront/basket/urls.py
from django.conf.urls import url
from . import views
from orders.views import update_new_order
from django.views.generic import TemplateView

app_name = 'basket'

urlpatterns = [

    url(r'^$',views.BasketMain.as_view(),name='basket'),
    url(r'^x/$',views.BasketTemp.as_view(),name='basketx'),
    url(r'^(?P<pk>\d+)/$',views.BasketDetail.as_view(),name='basket_detail'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/delete/$',views.BasketBouquetDelete.as_view(),name='delete_bouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/tdelete/$',views.BasketTBouquetDelete.as_view(),name='delete_tbouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/rdelete/$',views.BasketRBouquetDelete.as_view(),name='delete_rbouquet'),
    url(r'^confirm/create/$',views.CreateAccountFromBasket.as_view(),name='purchase'),
    url(r'^confirm/final/$',update_new_order,name='purchase_final'),
    url(r'^confirm/(?P<pk>\d+)/update/$',views.UpdateAccountFromBasket.as_view(),name="update_purchase"),

    # url(r'^create/(?P<b_model>[-\w]+)/(?P<pk>\d+)/$',views.CreateBasket.as_view(),name='create_basket'),
]

storefront/orders/urls.py
from django.conf.urls import url
from . import views


app_name = 'orders'

urlpatterns = [
    url(r'^detail/(?P<pk>\d+)/$',views.OrderDetail.as_view(),name='detail'),
]

storefront/products/urls.py
from django.conf.urls import url
from . import views
from themed_products.views import RandomCreateThemedBouquet

app_name = 'products'

urlpatterns = [

    url(r'^main/$',RandomCreateThemedBouquet.as_view(),name="shop"),
    url(r'^range/$',views.RangeHome.as_view(),name='range'),
    url(r'^tailor/$',views.create_bouquet,name='tailor'),
    url(r'^(?P<bouquet_id>\d+)/create/single/$',views.FlowerCreate.as_view(),name="create_single"),
    url(r'^(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/single/$',views.FlowerDelete.as_view(),name="delete_flower"),
    url(r'^bouquet/(?P<pk>\d+)/$',views.BouquetDetail.as_view(),name="detail_bouquet"),
    url(r'^bouquetup/(?P<pk>\d+)/$',views.update_bouquet,name='update_bouquet_new'),
    url(r'^bouquet/(?P<pk>\d+)/delete/$',views.DeleteBouquet.as_view(),name="delete_bouquet"),
    url(r'^bouquetb/(?P<pk>\d+)/$',views.BasketBouquetDetail.as_view(),name="basket_bouquet"),

    # url(r'^bouquet/(?P<pk>\d+)/update/$',views.UpdateBouquet.as_view(),name="update_bouquet"),
    # url(r'^bouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateBouquetTwo.as_view(),name="update_bouquet_two"),
]

storefront/range_products/urls.py
from django.conf.urls import url
from . import views


app_name = 'range_products'


urlpatterns = [

    url(r'^create/(?P<range_name>[-\w]+)/(?P<slug>[-\w]+)/$', views.create_range_bouquet,name='create_one'),
    url(r'^list/(?P<range_name>[-\w]+)/$',views.RangeBouquetList.as_view(),name='range_list'),
    url(r'^detail/(?P<pk>\d+)/$',views.RangeBouquetDetail.as_view(),name='r_bouquet_detail'),

    ### User doesn't have a basket:
    # url(r'^create/(?P<range_name>[-\w]+)/(?P<slug>[-\w]+)/$', views.CreateRangeBouquet.as_view(),name='create_one'),
    ### User already has a basket:
    # url(r'^create2/(?P<range_name>[-\w]+)/(?P<slug>[-\w]+)/$', views.CreateRangeBouquetTwo.as_view(),name='create_two'),
]

storefront/storefront/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    url(r'^$',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls, name='myadmin'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^loggedin/$',views.LoggedInPage.as_view(),name='logged_in'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^about/$',views.AboutPage.as_view(),name='about'),
    url(r'^basket/',include('basket.urls',namespace='basket')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^themed_products/',include('themed_products.urls',namespace='themed_products')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^range_products/',include('range_products.urls',namespace='range_products')),
    url(r'^enquiry/',include('enquiry.urls',namespace='enquiry')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storefront/themed_products/urls.py
from django.conf.urls import url
from . import views

app_name = 'themed_products'

urlpatterns = [

    url(r'^create/$',views.CreateThemedBouquet.as_view(),name="create_themed"),
    url(r'^tbouquetty/update/(?P<b_id>\d+)/$',views.CreateTypeTheme.as_view(),name="update_type"),
    url(r'^tbouquetc/update/(?P<b_id>\d+)/$',views.CreateColourTheme.as_view(),name="update_colour"),
    url(r'^tbouquetth/(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/$',views.DeleteTheme.as_view(),name="delete_theme"),
    url(r'^tbouquet/(?P<pk>\d+)/$',views.ThemedBouquetDetail.as_view(),name="themed_detail"),
    url(r'^tbouquetb/(?P<pk>\d+)/$',views.BasketThemedBouquetDetail.as_view(),name="basket_tbouquet"),
    url(r'^tbouquet/(?P<pk>\d+)/update/$',views.update_themed_bouquet,name='update_tbouquet'),
    url(r'^tbouquet/(?P<pk>\d+)/delete/$',views.DeleteThemedBouquet.as_view(),name="delete_tbouquet"),
    url(r'^rbouquet/(?P<pk>\d+)/update/$',views.RandomUpdateThemedBouquet.as_view(),name="random_update"),

    # url(r'^tbouquet/(?P<pk>\d+)/update/$',views.UpdateTBouquet.as_view(),name="update_tbouquet"),
    # url(r'^tbouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateTBouquetTwo.as_view(),name="update_tbouquet_two"),
    ]

storefront/products/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib import auth
from decimal import Decimal
from basket.models import Basket
from orders.models import Order

from django import template
register = template.Library()

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.

class Colour(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2,max_digits=8)

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2,max_digits=8)

    def __str__(self):
        return self.name


class Bouquet(models.Model):
    price = models.DecimalField(decimal_places=2,max_digits=8,default=Decimal('0.00'))
    basket = models.ForeignKey(Basket,on_delete=models.CASCADE,blank=True,null=True,related_name='bouquet')
    order = models.ForeignKey(Order,on_delete=models.CASCADE,blank=True,null=True,related_name='bouquet')

    def __str__(self):
        return f"Bouquet #{self.pk}"

    def get_absolute_url(self):
        return reverse('products:detail_bouquet',kwargs= {'pk':self.pk})


class Flower(models.Model):
    type = models.ForeignKey(Type,on_delete=models.CASCADE,related_name='flower_type')
    colour = models.ForeignKey(Colour,on_delete=models.CASCADE,related_name='flower_colour')
    price = models.DecimalField(blank=True,decimal_places=2,max_digits=8)
    bouquet = models.ForeignKey(Bouquet,on_delete=models.CASCADE,related_name='flower',null=True)

    def __str__(self):
        return f"{self.colour} {self.type}".title()

    def get_absolute_url(self):
        return reverse('products:detail_bouquet',kwargs={'pk':self.bouquet.pk})

storefront/products/forms.py
from django import forms
from . import models
from django.forms import ModelForm


# Create your forms here:


class CreateFlowerForm(ModelForm):

    class Meta:
        model = models.Flower
        fields = ('type','colour')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['type'].label = 'Select a flower:'
        self.fields['colour'].label = 'Select a colour:'


class CreateBouquetForm(ModelForm):

    class Meta:
        model = models.Bouquet
        exclude = ('basket','price','order',)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)


class UpdateBouquetForm(ModelForm):

    class Meta:
        model = models.Bouquet
        exclude = ('price','basket','order',)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

storefront/products/views.py
from django.shortcuts import render,redirect
from django.views.generic import (CreateView, DetailView,
                                TemplateView, UpdateView,
                                DeleteView,)
from . import models
from . import forms
from basket.models import Basket
from .models import Type
from django.urls import reverse_lazy
import re


# Create your views here.

class FlowerCreate(CreateView):
    model = models.Flower
    form_class = forms.CreateFlowerForm
    template_name = 'products/create_flower.html'

    def get_context_data(self):
        context = super().get_context_data()
        b1 = self.request.META.get('HTTP_REFERER')
        b2 = re.findall(r'/\d+',b1)[-1]
        b3 = re.findall(r'\d+',b2)[0]
        context['prev'] = b3
        return context

    def form_valid(self,form):
        b1 = self.request.META.get('HTTP_REFERER')
        self.object = form.save(commit=False)
        self.object.price = self.object.type.price + self.object.colour.price
        b2 = re.findall(r'/\d+',b1)[-1]
        b3 = re.findall(r'\d+',b2)[0]
        self.object.bouquet = models.Bouquet.objects.get(id__iexact=b3)
        self.object.save()
        return super().form_valid(form)


class FlowerDelete(DeleteView):
    model = models.Flower
    template_name = 'products/delete_flower.html'

    def get_success_url(self,**kwargs):
        b1 = self.request.META.get('HTTP_REFERER')
        b2 = re.findall(r'/\d+',b1)[-1]
        b3 = re.findall(r'\d+',b2)[0]
        success_url = reverse_lazy('products:detail_bouquet',kwargs={'pk':b3})
        return success_url

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data()
        b1 = self.request.META.get('HTTP_REFERER')
        b2 = re.findall(r'/\d+',b1)[-1]
        b3 = re.findall(r'\d+',b2)[0]
        context['prev'] = b3
        return context


def create_bouquet(request):
    new_bouquet = forms.CreateBouquetForm()

    if request.method == "POST":
        new_bouquet = forms.CreateBouquetForm(request.POST)

        if new_bouquet.is_valid():
            b = new_bouquet.save(commit=True)
            print("New bouquet created!")
            return redirect('products:detail_bouquet',pk=b.pk)
        else:
            print("Error - form invalid")

    return render(request,'products/tailor_home.html',{'bouquet_form': new_bouquet})


class BouquetDetail(DetailView):
    model = models.Bouquet
    template_name = 'products/tailor_flower.html'

    def get_context_data(self, **kwargs):
        context = super(BouquetDetail, self).get_context_data(**kwargs)
        result = 0
        for flower in self.object.flower.all():
            result += flower.price
        context['total'] = result
        return context


def update_bouquet(request,pk):
    bpk = pk
    object = models.Bouquet.objects.get(id=bpk)
    update_form = forms.UpdateBouquetForm()
    update_form.instance = object

    if request.method == "POST":
        update_form = forms.UpdateBouquetForm(request.POST)

        if update_form.is_valid():
            result = 0
            for flower in object.flower.all():
                result += flower.price
            object.price = result
            x = Basket.objects.get_or_create(user=request.user)[0]
            x.save()
            object.basket = x
            object.save()
            print("Bouquet updated")
            return redirect('basket:basket')
        else:
            print("Error - form invalid")

    return render(request,'products/update_bouquet.html', {'update_form': update_form,'bouquet_pk':pk})


class DeleteBouquet(DeleteView):
    model = models.Bouquet
    template_name = 'products/delete_bouquet.html'
    success_url = reverse_lazy('products:shop')


class BasketBouquetDetail(DetailView):
    model = models.Bouquet
    template_name = 'products/basket_bouquet_detail.html'


class ShopMain(TemplateView):
    template_name = 'products/shop_main.html'


class RangeHome(TemplateView):
    template_name = 'products/range_home.html'


### Update (condition: user doesn't have basket):

# class UpdateBouquet(UpdateView):
#     model = models.Bouquet
#     form_class = forms.UpdateBouquetForm
#     template_name = 'products/update_bouquet.html'
#
#     def get_success_url(self):
#         success_url = reverse_lazy('basket:create_basket', kwargs={'b_model':'b','pk':self.object.pk})
#         return success_url
#
#     def form_valid(self,form):
#         self.object = form.save(commit=False)
#         result = 0
#         for flower in self.object.flower.all():
#             result += flower.price
#         self.object.price = result
#         self.object.save()
#         return super().form_valid(form)

#####################


### Update (condition: user already has basket):
# class UpdateBouquetTwo(UpdateView):
#     model = models.Bouquet
#     form_class = forms.UpdateBouquetForm
#     template_name = 'products/update_bouquet.html'
#     success_url = reverse_lazy('basket:basket')
#
#     def form_valid(self,form):
#         self.object = form.save(commit=False)
#         result = 0
#         for flower in self.object.flower.all():
#             result += flower.price
#         self.object.price = result
#         self.object.basket = self.request.user.customer_basket
#         self.object.save()
#         return super().form_valid(form)

######################

storefront/products/templates/products/basket_bouquet_detail.html
{% extends 'site_base.html' %}

{% block content_block %}

<br>
<div class="container">
  <div class="row text-cen cen">
    <div class="col-lg-6 col-md-12 mx-auto col-sm-12 col-xs-12 pale-image thumb-border-full">
      <br><br>
        <h3 class="tb_title">Your bouquet:</h3>
          <br><br><br>
          {% for flower in object.flower.all %}
            <h6>{{flower}}</h5>
            <p>£{{flower.price}}</p>
          {% endfor %}
          <br><br>
          <h5>Total: £{{object.price}}</h5>
          <br><br>

        <br>

        {% if object.basket %}
          <a class="btn btn-outline-primary" href="{% url 'basket:basket' %}">Back to basket</a>
        {% else %}
        <a class="btn btn-outline-primary" href="{% url 'orders:detail' pk=object.order.pk %}">Back to order</a>
        {% endif %}

        <br><br>
    </div>
  </div>
</div>

{% endblock %}

storefront/products/templates/products/range_home.html
{% extends 'site_base.html' %}
{% load static %}

{% block content_block %}

<img src="{% static "images/titles/header3rangefinal.jpg" %}" style="max-width:100%;height:auto;" alt="Error loading photo">
<br><br>

<div class="container">

  <div class="row thumb-border-rng range-flex">
      <button class="rng-button" style="border:white;padding-bottom:10px;" type="button">
        <a class="lnk" href="{% url 'range_products:range_list' range_name='wild'%}">
        <h5 class="cen">Wild</h5></a>
      </button>
          <div class="col-lg-4 col-sm-4 col-xs-6 text-cen rng cen">
            <div>
              <a href="{% url 'range_products:range_list' range_name='wild'%}">
              <img class="img-thumbnail img-fluid rng" src="{% static "images/range/Wild.jpg" %}" alt="Error loading photo" href="{% url 'range_products:range_list' range_name='wild' %}">
              </a>
            </div>
          </div>
          <div class="col-lg-4 col-sm-4 col-xs-6 text-cen rng cen">
            <div>
              <a href="{% url 'range_products:range_list' range_name='wild'%}">
              <img class="img-thumbnail img-fluid rng" src="{% static "images/range/Wild colour crop.jpg" %}" alt="Error loading photo">
              </a>
            </div>
          </div>
          <div class="col-lg-4 col-sm-4 col-xs-6 text-cen rng cen">
            <div>
              <a href="{% url 'range_products:range_list' range_name='wild'%}">
              <img class="img-thumbnail img-fluid rng" src="{% static "images/range/Wild blues.jpg" %}" alt="Error loading photo">
              </a>
            </div>
          </div>
    </div>

  <br>

  <div class="row thumb-border-rng range-flex">
      <button class="rng-button" style="border:white;padding-bottom:10px;" type="button">
        <a class="lnk" href="{% url 'range_products:range_list' range_name='Valentines' %}">
          <h5 class="cen">Valentines</h5></a>
      </button>
          <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
            <div>
              <a href="{% url 'range_products:range_list' range_name='Valentines' %}">
              <img class="img-thumbnail img-fluid rng" src="{% static "images/range/Valentines3.jpg" %}" alt="Error loading photo">
              </a>
            </div>
          </div>
          <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
            <div>
              <a href="{% url 'range_products:range_list' range_name='Valentines' %}">
              <img class="img-thumbnail img-fluid rng" src="{% static "images/range/Valentines1.jpg" %}" alt="Error loading photo">
              </a>
            </div>
          </div>
          <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
            <div>
              <a href="{% url 'range_products:range_list' range_name='Valentines' %}">
              <img class="img-thumbnail img-fluid rng" src="{% static "images/range/Valentines2crop.jpg" %}" alt="Error loading photo">
              </a>
            </div>
          </div>
    </div>

  <br>

  <div class="row thumb-border-rng range-flex">
        <button class="rng-button" style="border:white;padding-bottom:10px;" type="button">
          <a class="lnk" href="{% url 'range_products:range_list' range_name='neutral' %}">
          <h5 class="cen">Neutral</h5></a>
        </button>
          <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
              <div>
                <a href="{% url 'range_products:range_list' range_name='neutral' %}">
                <img class="img-thumbnail img-fluid rng" src="{% static "images/range/neutral5.jpg" %}" alt="Error loading photo">
                </a>
              </div>
            </div>
          <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
              <div>
                <a href="{% url 'range_products:range_list' range_name='neutral' %}">
                <img class="img-thumbnail img-fluid rng" src="{% static "images/range/neutral4.jpg" %}" alt="Error loading photo">
                </a>
              </div>
          </div>
          <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
              <div>
                <a href="{% url 'range_products:range_list' range_name='neutral' %}">
                <img class="img-thumbnail img-fluid rng" src="{% static "images/range/neutral3.jpg" %}" alt="Error loading photo">
                </a>
              </div>
            </div>
    </div>

  <br>

  <div class="row thumb-border-rng range-flex">
      <button class="rng-button" style="border:white;padding-bottom:10px;" type="button">
        <a class="lnk" href="{% url 'range_products:range_list' range_name='unusual' %}">
          <h5 class="cen">Unusual</h5></a>
      </button>
      <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
        <div>
          <a href="{% url 'range_products:range_list' range_name='unusual' %}">
          <img class="img-thumbnail img-fluid rng" src="{% static "images/range/unusual1.jpg" %}" alt="Error loading photo">
          </a>
        </div>
      </div>
      <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
        <div>
          <a href="{% url 'range_products:range_list' range_name='unusual' %}">
          <img class="img-thumbnail img-fluid rng" src="{% static "images/range/unusual3.jpg" %}" alt="Error loading photo">
          </a>
        </div>
      </div>
      <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
        <div>
          <a href="{% url 'range_products:range_list' range_name='unusual' %}">
          <img class="img-thumbnail img-fluid rng" src="{% static "images/range/unusual2.jpg" %}" alt="Error loading photo">
          </a>
        </div>
      </div>
  </div>

  <br>

  <div class="row thumb-border-rng range-flex">
      <button class="rng-button" style="border:white;padding-bottom:10px;" type="button">
        <a class="lnk" href="{% url 'range_products:range_list' range_name='colourful' %}">
          <h5 class="cen">Colourful</h5></a>
      </button>
      <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
        <div>
          <a href="{% url 'range_products:range_list' range_name='colourful' %}">
          <img class="img-thumbnail img-fluid rng" src="{% static "images/range/colourful2.jpg" %}" alt="Error loading photo">
          </a>
        </div>
      </div>
      <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
        <div>
          <a href="{% url 'range_products:range_list' range_name='colourful' %}">
          <img class="img-thumbnail img-fluid rng" src="{% static "images/range/colourful5.jpg" %}" alt="Error loading photo">
          </a>
        </div>
      </div>
      <div class="col-lg-4 col-sm-4 col-xs-6 rng cen">
        <div>
          <a href="{% url 'range_products:range_list' range_name='colourful' %}">
          <img class="img-thumbnail img-fluid rng" src="{% static "images/range/colourful6.jpg" %}" alt="Error loading photo">
          </a>
        </div>
      </div>
  </div>

</div>

<br><br>

<div class="cen text-cen">
    <a class="btn btn-outline-danger" href="{% url 'products:shop' %}">Back</a>
</div>

<br><br><br>

{% endblock %}

storefront/products/templates/products/shop_main.html
{% extends 'site_base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block content_block %}

<br>
    <img class="header-image" src="{% static "images/titles/NewestShop.jpg" %}" style="max-width:100%;height:auto;" alt="Error loading photo">
<br><br>

<div class="container width-full" style="padding-left:0px;padding-right:0px;">
  <div class="row">
    <div class="col-lg-4 col-sm-4 col-xs-6 cen">
      <a class="btn btn-outline-success" style="width:100%;border-top:2px solid green;border-bottom:2px solid green" href="{% url 'products:range' %}">Browse our range</a>
      <br>
    </div>
    <div class="col-lg-4 col-sm-4 col-xs-6 cen">
      <a class="btn btn-outline-success btn-block" style="width:100%" href="{% url 'products:tailor' %}">Design your own bouquet</a>
      <br>
    </div>
    <div class="col-lg-4 col-sm-4 col-xs-6 cen">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-outline-success" style="width:100%;border-top:2px solid green;border-bottom:2px solid green" type="submit" value="Surprise me!">
      </form>
    </div>
  </div>
</div>
<br><br>

{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">

storefront/products/templates/products/tailor_flower.html
{% extends 'site_base.html' %}

{% block content_block %}

{% if bouquet.flower.count < 1 %}

<br><br>
<br>
<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image text-cen">
      <br><br><br>
      <h5>No flowers in your bouquet yet!</h5>
      <br><br><br>
      <h5>Total: £{{bouquet.price}}</h5>
      <br><br><br>
    </div>
  </div>
</div>

{% else %}

<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image text-cen">
      <br><br><br>
      <h3 class="tb_title">In your bouquet:</h3>
      <br><br><br>
        {% for flower in bouquet.flower.all %}
          <h6>{{flower}}</h5>
          <p>£{{flower.price}}</p>
          <a class="btn btn-outline-danger btn-sm" href="{% url 'products:delete_flower' pk=flower.pk bouquet_id=bouquet.pk %}">Delete</a>
            <br><br><br>
        {% endfor %}
        <h5>Total: £{{total}}</h5>
        <br><br>
      </div>
    </div>
  </div>

{% endif %}

<div class="container-fluid">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 text-cen">
      <div class="row text-cen cen">
          <div class="col text-cen">
          <h6 class="text-cen cen"><a class="btn btn-outline-danger" href="{% url 'products:delete_bouquet' pk=bouquet.pk %}">Discard all</a></h6>
            </div>
          <div class="col text-cen">
          <h6 class="text-cen cen"> <a class="btn btn-outline-primary" href="{% url 'products:create_single' bouquet_id=bouquet.pk %}">Add a flower</a></h6>
            </div>

          <div class="col text-cen">
            {% if user.customer_basket %}
            <h6 class="text-cen cen"><a class="btn btn-outline-success" href="{% url 'products:update_bouquet_new' pk=bouquet.pk %}">Save bouquet</a></h6>
            {% else %}
            <h6 class="text-cen cen"><a class="btn btn-outline-success" href="{% url 'products:update_bouquet_new' pk=bouquet.pk %}">Save bouquet</a></h6>
            {% endif %}
              </div>

      </div>
    </div>
  </div>
</div>
<br>

{% endblock %}

storefront/products/templates/products/tailor_home.html
{% extends 'site_base.html' %}
{% load static %}

{% block content_block %}


<img src="{% static "images/titles/DesignBouq2JPG.jpg" %}" style="max-width:100%;height:auto;" alt="Error loading photo">

<br><br>
<div class="container" style="padding-left:0px;padding-right:0px;">
  <div class="row">
    <div class="col-lg-6 col-sm-12 col-xs-12">
        <a href="{% url 'themed_products:create_themed' %}"><img class="img-fluid myborder" src="{% static "images/titles/123456.jpg" %}" alt="Error loading photo"></a>
        <br>
    </div>
      <div class="col-lg-6 col-sm-12 col-xs-12">
        <form class="create-bouquet" method="post">
          {{bouquet_form.as_p}}
          {% csrf_token %}
          <input type="image" class="img-fluid myborder" src="{% static "images/titles/flowers3.jpg" %}" alt="Tailor flower by flower">
        </form>
        </div>
    </div>
</div>
<br><br>

{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">