storefront/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
    url(r'^create/$',views.CreateAccount.as_view(),name='create'),
    url(r'^details/(?P<pk>\d+)/$',views.DisplayDetails.as_view(),name='details'),
    url(r'^edit/(?P<pk>\d+)/$',views.EditAccount.as_view(),name='edit'),

]

storefront/basket/urls.py
from django.conf.urls import url
from . import views
from orders.views import update_new_order
from django.views.generic import TemplateView

app_name = 'basket'

urlpatterns = [

    url(r'^$',views.BasketMain.as_view(),name='basket'),
    url(r'^x/$',views.BasketTemp.as_view(),name='basketx'),
    url(r'^(?P<pk>\d+)/$',views.BasketDetail.as_view(),name='basket_detail'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/delete/$',views.BasketBouquetDelete.as_view(),name='delete_bouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/tdelete/$',views.BasketTBouquetDelete.as_view(),name='delete_tbouquet'),
    url(r'^(?P<pk>\d+)/(?P<basket_id>\d+)/rdelete/$',views.BasketRBouquetDelete.as_view(),name='delete_rbouquet'),
    url(r'^confirm/create/$',views.CreateAccountFromBasket.as_view(),name='purchase'),
    url(r'^confirm/final/$',update_new_order,name='purchase_final'),
    url(r'^confirm/(?P<pk>\d+)/update/$',views.UpdateAccountFromBasket.as_view(),name="update_purchase"),

    # url(r'^create/(?P<b_model>[-\w]+)/(?P<pk>\d+)/$',views.CreateBasket.as_view(),name='create_basket'),
]

storefront/products/urls.py
from django.conf.urls import url
from . import views
from themed_products.views import RandomCreateThemedBouquet

app_name = 'products'

urlpatterns = [

    url(r'^main/$',RandomCreateThemedBouquet.as_view(),name="shop"),
    url(r'^range/$',views.RangeHome.as_view(),name='range'),
    url(r'^tailor/$',views.create_bouquet,name='tailor'),
    url(r'^(?P<bouquet_id>\d+)/create/single/$',views.FlowerCreate.as_view(),name="create_single"),
    url(r'^(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/single/$',views.FlowerDelete.as_view(),name="delete_flower"),
    url(r'^bouquet/(?P<pk>\d+)/$',views.BouquetDetail.as_view(),name="detail_bouquet"),
    url(r'^bouquetup/(?P<pk>\d+)/$',views.update_bouquet,name='update_bouquet_new'),
    url(r'^bouquet/(?P<pk>\d+)/delete/$',views.DeleteBouquet.as_view(),name="delete_bouquet"),
    url(r'^bouquetb/(?P<pk>\d+)/$',views.BasketBouquetDetail.as_view(),name="basket_bouquet"),

    # url(r'^bouquet/(?P<pk>\d+)/update/$',views.UpdateBouquet.as_view(),name="update_bouquet"),
    # url(r'^bouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateBouquetTwo.as_view(),name="update_bouquet_two"),
]

storefront/range_products/urls.py
from django.conf.urls import url
from . import views


app_name = 'range_products'


urlpatterns = [

    url(r'^create/(?P<range_name>[-\w]+)/(?P<slug>[-\w]+)/$', views.create_range_bouquet,name='create_one'),
    url(r'^list/(?P<range_name>[-\w]+)/$',views.RangeBouquetList.as_view(),name='range_list'),
    url(r'^detail/(?P<pk>\d+)/$',views.RangeBouquetDetail.as_view(),name='r_bouquet_detail'),

    ### User doesn't have a basket:
    # url(r'^create/(?P<range_name>[-\w]+)/(?P<slug>[-\w]+)/$', views.CreateRangeBouquet.as_view(),name='create_one'),
    ### User already has a basket:
    # url(r'^create2/(?P<range_name>[-\w]+)/(?P<slug>[-\w]+)/$', views.CreateRangeBouquetTwo.as_view(),name='create_two'),
]

storefront/storefront/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    url(r'^$',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls, name='myadmin'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^loggedin/$',views.LoggedInPage.as_view(),name='logged_in'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^about/$',views.AboutPage.as_view(),name='about'),
    url(r'^basket/',include('basket.urls',namespace='basket')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^themed_products/',include('themed_products.urls',namespace='themed_products')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^range_products/',include('range_products.urls',namespace='range_products')),
    url(r'^enquiry/',include('enquiry.urls',namespace='enquiry')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storefront/themed_products/urls.py
from django.conf.urls import url
from . import views

app_name = 'themed_products'

urlpatterns = [

    url(r'^create/$',views.CreateThemedBouquet.as_view(),name="create_themed"),
    url(r'^tbouquetty/update/(?P<b_id>\d+)/$',views.CreateTypeTheme.as_view(),name="update_type"),
    url(r'^tbouquetc/update/(?P<b_id>\d+)/$',views.CreateColourTheme.as_view(),name="update_colour"),
    url(r'^tbouquetth/(?P<pk>\d+)/(?P<bouquet_id>\d+)/delete/$',views.DeleteTheme.as_view(),name="delete_theme"),
    url(r'^tbouquet/(?P<pk>\d+)/$',views.ThemedBouquetDetail.as_view(),name="themed_detail"),
    url(r'^tbouquetb/(?P<pk>\d+)/$',views.BasketThemedBouquetDetail.as_view(),name="basket_tbouquet"),
    url(r'^tbouquet/(?P<pk>\d+)/update/$',views.update_themed_bouquet,name='update_tbouquet'),
    url(r'^tbouquet/(?P<pk>\d+)/delete/$',views.DeleteThemedBouquet.as_view(),name="delete_tbouquet"),
    url(r'^rbouquet/(?P<pk>\d+)/update/$',views.RandomUpdateThemedBouquet.as_view(),name="random_update"),

    # url(r'^tbouquet/(?P<pk>\d+)/update/$',views.UpdateTBouquet.as_view(),name="update_tbouquet"),
    # url(r'^tbouquet/(?P<pk>\d+)/updatetwo/$',views.UpdateTBouquetTwo.as_view(),name="update_tbouquet_two"),
    ]

storefront/basket/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib import auth
from decimal import Decimal

from django import template
register = template.Library()


# Create your models here.

class Basket(models.Model):

    total = models.DecimalField(decimal_places=2,max_digits=8,null=True,blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,related_name='customer_basket',on_delete=models.CASCADE)
    b_id_num = models.PositiveIntegerField(null=True,blank=True)

    def __str__(self):
        return f"{self.user}'s basket"

    def get_absolute_url(self):
        return reverse('basket:basket')

storefront/basket/forms.py
# from django import forms
# from . import models
# from django.forms import ModelForm
# from django.forms.widgets import HiddenInput
#
#
# class CreateBasketForm(ModelForm):
#
#     b_id_num = forms.IntegerField(max_value=None,min_value=1,widget=forms.HiddenInput())
#
#     class Meta:
#         model = models.Basket
#         exclude = ('user','order','total')
#
#     def __init__(self,*args,**kwargs):
#         super().__init__(*args,**kwargs)

storefront/basket/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, CreateView,
                                  DetailView, UpdateView,
                                  DeleteView,)
from .models import Basket
from . import forms
from accounts.models import Account
from products.models import Bouquet
from orders.models import Order
from themed_products.models import ThemedBouquet
from range_products.models import RangeBouquet, Range
from django.urls import reverse_lazy
# import re
from django.contrib.auth import get_user_model
User = get_user_model()


# Create your views here.


class BasketDetail(DetailView):
    model = Basket
    template_name = "basket/basket_detail.html"


class BasketMain(CreateView):
    model = Order
    template_name = "basket/basket.html"
    fields = ()

    def get_success_url(self,**kwargs):
        success_url = reverse_lazy('basket:purchase_final')
        return success_url

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.account = self.request.user.customer_account
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self,*args,**kwargs):
        context = super(BasketMain,self).get_context_data(**kwargs)
        b = Bouquet.objects.filter(basket=self.request.user.customer_basket)
        tb = ThemedBouquet.objects.filter(basket=self.request.user.customer_basket)
        r = RangeBouquet.objects.filter(basket=self.request.user.customer_basket)
        result = 0
        if len(b) > 0:
            for x in b:
                result += x.price
        if len(tb) > 0:
            for x in tb:
                result += x.price
        if len(r) > 0:
            for x in r:
                result += x.price
        context = {'b':b,'tb':tb,'r':r,'total':result}
        return context


class BasketTemp(TemplateView):
    template_name = "basket/basket_temp.html"


class BasketBouquetDelete(DeleteView):
    model = Bouquet
    template_name = 'basket/basket_bouquet_delete.html'
    success_url = reverse_lazy('basket:basket')


class BasketTBouquetDelete(DeleteView):
    model = ThemedBouquet
    template_name = 'basket/basket_bouquet_delete.html'
    success_url = reverse_lazy('basket:basket')


class BasketRBouquetDelete(DeleteView):
    model = RangeBouquet
    template_name = 'basket/basket_bouquet_delete.html'
    success_url = reverse_lazy('basket:basket')


class CreateAccountFromBasket(LoginRequiredMixin,CreateView):
    model = Account
    fields = ['first_name','surname','billing_address','delivery_address']
    template_name = 'accounts/create_account.html'
    success_url = reverse_lazy('basket:basket')

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class UpdateAccountFromBasket(LoginRequiredMixin,UpdateView):
    model = Account
    fields = ['first_name','surname','billing_address','delivery_address']
    template_name = 'accounts/edit_details.html'

    def get_success_url(self,**kwargs):
        success_url = reverse_lazy('basket:basket')
        return success_url



# class CreateBasket(CreateView):
#     model = Basket
#     form_class = forms.CreateBasketForm
#     template_name = 'basket/create_basket.html'
#
#     def get_success_url(self,**kwargs):
#         bas = self.request.user.customer_basket
#         if self.kwargs['b_model']== 'b':
#             success_url = reverse_lazy('products:update_bouquet_two', kwargs={'pk':bas.b_id_num})
#         elif self.kwargs['b_model']== 'tb':
#             success_url = reverse_lazy('themed_products:update_tbouquet_two', kwargs={'pk':bas.b_id_num})
#         else:
#             success_url = reverse_lazy('range_products:update_rbouquet', kwargs={'pk':bas.b_id_num})
#         return success_url
#
#     def get_context_data(self, **kwargs):
#         context = super(CreateBasket,self).get_context_data(**kwargs)
#         b1 = self.request.META.get('HTTP_REFERER')
#
#         b2 = re.findall(r'/\d+',b1)[-1]
#         b3 = re.findall(r'\d+',b2)[0]
#         context['bouq'] = b3
#
#         res = False
#         pattern = ['tbouquet']
#         if re.search(pattern[0],b1):
#             res = True
#         context['tb'] = res
#
#         pattern3 = ['/[-\w]+']
#         range_results = []
#         range_results = re.findall(pattern3[0],b1)
#         range_results2 = [x.strip('/') for x in range_results]
#         rb = False
#         if self.kwargs['b_model'] == 'r':
#             rb = True
#         context['r'] = rb
#         context['rng_nm'] = range_results2[-2]
#         context['r_slug'] = range_results2[-1]
#         return context
#
#     def get_initial(self,**kwargs):
#         initial = super().get_initial()
#         b1 = self.kwargs['pk']
#         initial['b_id_num'] = b1
#         return initial
#
#     def get_queryset(self):
#         return Range.objects.all()
#
#     def form_valid(self,form):
#         self.object = form.save(commit=False)
#         self.object.user = self.request.user
#         self.object.b_id_num = form.cleaned_data['b_id_num']
#         self.object.save()
#         return super().form_valid(form)

storefront/basket/templates/basket/basket.html
{% extends 'site_base.html' %}

{% block content_block %}


  {% if user.customer_basket %}
    {% include 'basket/basket_detail.html' with bou='bou' %}
  {% else %}
    <h6>Your basket is empty</h6>
  {% endif %}


{% endblock %}

storefront/basket/templates/basket/basket_bouquet_delete.html
{% extends 'site_base.html' %}

{% block content_block %}

<br><br>
<br><br>
<div class="container">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-6 pale-image thumb-border-full">
        <br><br>
        <h5>Are you sure you want to delete this bouquet?</h5>
          <br><br>

        <form method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-outline-success" value="Delete">
        </form>
        <br>
        <h6><a class="btn btn-outline-danger" href="{% url 'basket:basket' %}">Cancel</a></h6>
        <br>
    </div>
  </div>
</div>

{% endblock %}

storefront/basket/templates/basket/basket_detail.html
{% if user.is_authenticated %}

<br><br>
<div class="container">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image thumb-border-full">

        <br><br>
        <h3 class="tb_title_b">{{user.customer_basket}}</h3>
          <br><br>

          {% if b %}
              {% for x in b %}
                <h6>{{x}}</h6>
                <p>£{{x.price}}</p>
                <a class="btn btn-outline-success btn-sm" href="{% url 'products:basket_bouquet' pk=x.pk %}">Details</a>
                  <a class="btn btn-outline-danger btn-sm" href="{% url 'basket:delete_bouquet' basket_id=user.customer_basket.pk pk=x.pk %}">Delete</a>
                  <br><br>
              {% endfor %}
          {% endif %}

          {% if tb %}
              {% for x in tb %}
                <h6>{{x}}</h6>
                <p>£{{x.price}}</p>
                <a class="btn btn-outline-success btn-sm" href="{% url 'themed_products:basket_tbouquet' pk=x.pk %}">Details</a>
                  <a class="btn btn-outline-danger btn-sm" href="{% url 'basket:delete_tbouquet' basket_id=user.customer_basket.pk pk=x.pk %}">Delete</a>
                  <br><br>
              {% endfor %}
          {% endif %}

          {% if r %}
              {% for x in r %}
                <h6>{{x|title}} bouquet</h6>
                <p>£{{x.price}}</p>
                <a class="btn btn-outline-success btn-sm" href="{% url 'range_products:r_bouquet_detail' pk=x.pk %}">Details</a>
                  <a class="btn btn-outline-danger btn-sm" href="{% url 'basket:delete_rbouquet' basket_id=user.customer_basket.pk pk=x.pk %}">Delete</a>
                  <br><br>
              {% endfor %}
          {% endif %}

          {% if b or tb or r %}
          <br><br>
            <h5>Total: £{{total}}</h5>
                <br><br>

              {% if user.customer_account %}
                <form method="post">
                  {% csrf_token %}
                  {{form.as_p}}
                  <input class="btn btn-outline-success" type="submit" value="Go to Checkout">
                </form>
                <br>
                <a class="btn btn-outline-primary" href="{% url 'products:shop' %}">Continue shopping</a>
                <br><br>

                {% else %}
                <a class="btn btn-outline-success" href="{% url 'basket:purchase' %}">Enter Delivery details and Checkout</a>
                <br><br>
                <br>
                <a class="btn btn-outline-primary" href="{% url 'products:shop' %}">Continue shopping</a>
                <br><br>
                {% endif %}

          {% else %}
            <br><br>
            <h5>Your basket is empty.</h5>
            <br><br>
          {% endif %}

      {% else %}

      <h6>Please sign up to place an order with us:</h6>
      <br><br>
      <a class="btn btn-outline-success" href="{% url 'accounts:signup' %}">Sign up</a>
    {% endif %}
    </div>
  </div>
  <br>
</div>

storefront/basket/templates/basket/basket_temp.html
{% extends 'site_base.html' %}

{% block content_block %}

<br><br><br>
<br>
<div class="container">
  <div class="row text-cen cen">
    <div class="col-lg-6 mx-auto col-md-12 col-sm-12 col-xs-12 pale-image thumb-border-full">
        <br><br>
        <h4>Your basket is empty.</h4>
        <br><br>
    </div>
  </div>
  <br>
</div>
<br>
{% endblock %}